---
- hosts: all
  remote_user: root
  vars:
    packages: docker
  tasks:
  - name: 1. copy sshkey
    authorized_key: 
      user: root 
      key: "{{ lookup('file', '/home/xuepz/.ssh/id_rsa.pub') }}"
    tags:
      - init
  - name: 2. yum upgrade OS
    yum: 
      name: '*'
      state: latest 
  - name: 3. Install docker
    yum:
      name: "{{packages}}"
      state: latest
  - name: 4. start docker
    service:
      name: docker
      state: started
      enabled: yes   
  - name: 5. disable swap
    command: '/usr/sbin/swapoff -a'
  - name: 6. delete the swap item from fstab  
    lineinfile:
      dest: /etc/fstab
      state: absent
      regexp: 'swap'