---
- hosts: all
  remote_user: root
  vars:
    packages: kubelet,kubeadm,kubectl
  tasks:
  - name: 1. add k8s repo
    yum_repository:
      name: kubernetes
      description: kubernetes
      file: k8s
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      proxy: https://proxy.p1.event.ibm.com:8080
      proxy_username: xuepz@cn.ibm.com
      proxy_password: Makepr0gress123
  - name: 2. install the packages
    yum:
      name: "{{packages}}"
      state: latest
  - name: 3. start kubelet
    service:
      name: kubelet
      state: started
      enabled: yes   
