---
- hosts: all
  remote_user: root
  vars:
    packages: kubelet,kubeadm,kubectl,lftp
  tasks:
  - name: 1. add k8s aliyun repo
    yum_repository:
      name: kubernetes
      description: kubernetes
      file: k8s
      baseurl: ftp://9.111.105.105/pub/k8s-repo/
      gpgcheck: no
      
  - name: 2. install the packages
    yum:
      name: "{{packages}}"
      state: latest
  - name: 3. start kubelet
    service:
      name: kubelet
      state: started
      enabled: yes       
  - name: ４.　rsync images
    command: lftp 9.111.105.105 -e "mirror pub/k8s-images/ . ;exit"
  - name: ５.　load images
    command: for i in *.tar; do docker load -i $i; done

