- hosts: master
  remote_user: root
  vars_prompt:
    - name: "username"
      prompt: "Insert User Name:"
      default: "xuepz"
      private: no
    - name: "passwd"
      prompt: "Insert Password for the user:"
      default: "use Python to hash"
      #python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
      private: no
  tasks:
#  - name: 1. modify sysctl if necessary
#    sysctl:
#      name: net.bridge.bridge-nf-call-iptables
#      value: 1
#      state: present
#      reload: yes
#      sysctl_file: /etc/sysctl.d/k8s.conf
#  - name: 2. kubeadmin init need logs
#    command: '/usr/bin/kubeadm init --apiserver-advertise-address 192.168.122.10 --pod-network-cidr 10.244.0.0/16 --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers'
  - name: 3. Create Remote User
    user: name="{{ username }}" password="{{ passwd }}"
    #become: yes
    #  password: "{{ 'item.pass'|password_hash('sha512') }}"

  - name: 4. modify sudoers  
    lineinfile:
      dest: /etc/sudoers
      insertafter: '^%wheel'
      line: 'xuepz ALL=(ALL) NOPASSWD: ALL'
  - name: 5. config kubeadmin files for user
    file:
      path: /home/xuepz/.kube
      state: directory
      owner: xuepz
      group: xuepz
  - name: 6. copy files
    command: 'cp /etc/kubernetes/admin.conf /home/xuepz/.kube/config'
  - name: 7. change permission
    file: 
      path: /home/xuepz/.kube/config
      owner: xuepz
      group: xuepz
  - name: 8. bash-auto-completion for kubeadmin
    lineinfile:
      dest: /home/xuepz/.bashrc
      insertafter: 'specific'
      line: 'source <(kubectl completion bash)'  
#  - name: 9. setup POD network
#    command: 'kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml'


    