apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
#  namespace: default
spec:
  accessModes:
  - ReadWriteMany 
  capacity:
    storage: 8Gi 
  persistentVolumeReclaimPolicy: Retain      #delete will remove the resource; retain: save recycle 
  storageClassName: nfs
  nfs:
    path: /var/nfs/pv
    server: 192.168.122.10
